module.exports = {
    siteUrl: process.env.NEXT_PUBLIC_ENV === "dev" ? 'http://localhost:3000' : "https://www.portoseguroingressos.com.br",
    generateRobotsTxt: true,
    generateIndexSitemap: false,
    sitemapSize: 50000,
    exclude: [
      '/adm-eventos',
      '/adm-organizadores',
      '/adm-pagamentos',
      '/adm-suporte',
      '/adm-transferencias',
      '/carteira',
      '/clientes',
      '/configuracoes',
      '/confirmar-social',
      '/cupons',
      '/dashboard',
      '/eventos/atualizar',
      '/eventos/criar',
      '/meu-perfil',
      '/meus-eventos',
      '/meus-ingressos',
      '/payouts',
      '/qr-scanner',
      '/redefinir-senha-log',
      '/suporte',
      '/cadastro-confirmar',
      '/checkout',
      '/qr-scanner-link',
      '/senha-redefinir',
      '/senha-redefinir-confirmar',
    ],
    robotsTxtOptions: {
      policies: [
        {
          userAgent: '*',
          allow: '/',
          disallow: [
            '/adm-eventos',
            '/adm-organizadores',
            '/adm-pagamentos',
            '/adm-suporte',
            '/adm-transferencias',
            '/carteira',
            '/clientes',
            '/configuracoes',
            '/confirmar-social',
            '/cupons',
            '/dashboard',
            '/eventos/atualizar',
            '/eventos/criar',
            '/meu-perfil',
            '/meus-eventos',
            '/meus-ingressos',
            '/payouts',
            '/qr-scanner',
            '/redefinir-senha-log',
            '/suporte',
            '/cadastro-confirmar',
            '/checkout',
            '/qr-scanner-link',
            '/senha-redefinir',
            '/senha-redefinir-confirmar',
          ],
        },
      ],
    },
  }