export const APIErrorHandler: Record<number, string> = {
    // INTERNAL
    1: "E-mail ou senha inválidos",
    2: "Senha atual incorreta",
    3: "E-mail já cadastrado",
    4: "Código de confirmação inválido",
    5: "Código para redefinição de senha já foi enviado",
    6: "E-mail não encontrado",
    7: "E-mail ainda não foi confirmado",
    8: "Já existe um cupom com este código para este evento",
    9: "Cupom inválido",
    10: "Este cupom não está mais ativo",
    11: "Este cupom já expirou",
    12: "Este cupom já atingiu o limite de uso",
    13: "Documento já cadastrado",
    14: "Quantidade não disponível para este dia do evento",
    15: "Quantidade não disponível para este tipo de ingresso",
    16: "Quantidade não disponível para este dia do evento e tipo de ingresso",
    17: "Quantidade não disponível para este evento",
    18: "Você está tentando diminuir a quantidade de ingressos de um lote que já vendeu mais ingressos do que a quantidade que você está tentando remover",
    19: "Senha incorreta",
    20: "QR Code do ingresso não está disponível",
    21: "Código de acesso inválido",
    22: "Sessão expirada",
    23: "Máximo de usuários atingido",
    24: "O número de parcelas não pode exceder o máximo de parcelas permitido para o evento",
    25: "Você atingiu o limite de compras de ingressos para este evento",
    26: "Sessão inexistente ou expirada",
    27: "Evento ainda não foi finalizado",
    28: "Não há saldo suficiente para realizar o saque",

    700: "Não é possível alterar datas do evento que já possuem ingressos vendidos. FALE COM O SUPORTE",
    701: "Não é possível alterar datas do evento que começarão em menos de 72 horas e já possuem ingressos vendidos. FALE COM O SUPORTE",
    702: "O tipo de recorrência não pode ser alterado.",
    703: "Não é possível alterar o horário de início da recorrência.",
    704: "Não é possível alterar o horário de término da recorrência.",
    705: "Não é possível alterar o dia da semana da recorrência.",
    706: "Não é possível alterar a data de início da recorrência.",
    707: "Não é possível alterar horários de início e término da recorrência.",
    708: "Não é possível alterar a data de início de vendas de um lote que já possui ingressos vendidos.",

    // EXTERNAL
    900: "Erro ao escrever a descrição do evento com IA",
    901: "Ocorreu algum erro ao tentar se autenticar com o Google",
    902: "Erro ao testar o pixel do Facebook",
    903: "Máximo de criações de descrição de evento com IA atingido hoje",
    904: "Ocorreu algum erro ao tentar escrever a descrição do evento com IA"
}